openai_key = "no-key" 
#chat_url = "http://192.168.1.221:8080/v1/chat/completions"
chat_url = "http://192.168.1.221:8080/completion"
model_name = "bartowski/Llama-3.2-3B-Instruct-GGUF:Q8_0"
proxy = false
log_level = "debug"

[mcp]
[[mcp.server]]
name = "document-indexing"
protocol = "sse"
url="http://192.168.1.29:8000/sse"
description = "A set of tools to assist in document indexing, mainly indexing and searching for documents"
